Task2, Criteria Search + dataJpaTest
disnaimov/warehouse pull request #6
Opened 2024-04-24 15:28 UTC by disnaimov

2024-04-24 15:39 UTC, disnaimov commented on pom.xml
Лишнее

2024-04-24 15:39 UTC, disnaimov commented on src/main/java/com/example/warehouse/WarehouseApplication.java
Лишнее

2024-04-24 15:39 UTC, disnaimov commented on src/main/java/com/example/warehouse/annotation/MethodExecutionTime.java
Лишнее

2024-04-24 15:39 UTC, disnaimov commented on src/main/java/com/example/warehouse/aspect/ExecutionTimeAspect.java
Лишнее

2024-04-24 15:40 UTC, disnaimov commented on src/main/java/com/example/warehouse/config/JdbcConfig.java
Лишнее

2024-04-24 15:40 UTC, disnaimov commented on src/main/java/com/example/warehouse/controllers/ProductRestController.java
Лишнее

2024-04-24 15:40 UTC, disnaimov commented on src/main/java/com/example/warehouse/dao/ProductRepository.java
Лишнее

2024-04-24 15:41 UTC, disnaimov commented on src/main/java/com/example/warehouse/entities/Product.java
Лишнее

2024-04-24 15:41 UTC, disnaimov commented on src/main/java/com/example/warehouse/hanlders/ProductServiceExceptionHandler.java
Лишнее

2024-04-24 15:41 UTC, disnaimov commented on src/main/java/com/example/warehouse/scheduler/OptimizedScheduler.java
Лишнее

2024-04-24 15:41 UTC, disnaimov commented on src/main/java/com/example/warehouse/scheduler/SchedulingManager.java
Лишнее

2024-04-27 12:02 UTC, GUR-ok commented
название мр сделать Task2: multycriterial search

2024-04-27 12:05 UTC, GUR-ok requested changes

2024-04-27 12:05 UTC, GUR-ok commented on pom.xml
> +			<groupId>org.springframework</groupId>
много лишних библиотек которые уже дают спрингбут стартеры
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <version>3.1.5</version>
        </dependency>
 ```

2024-04-27 12:05 UTC, GUR-ok commented on src/main/java/com/example/warehouse/WarehouseApplication.java
> +//@EnableScheduling
нужно было отпочковываться от девелоп а не от feature/task1

2024-04-27 12:05 UTC, GUR-ok commented on src/main/java/com/example/warehouse/scheduler/OptimizedScheduler.java
посмотрю после того, как вмержим feature/task1 или если уберешь отсюда все, что к 1 заданию..

2024-05-11 11:45 UTC, GUR-ok requested changes

2024-05-11 11:45 UTC, GUR-ok commented on src/main/java/com/example/warehouse/service/ProductService.java
> +                    if (fieldExpression.getJavaType() == BigDecimal.class || fieldExpression.getJavaType() == Integer.class) {
А если дата? Так нельзя делать.

2024-05-11 11:45 UTC, GUR-ok commented on src/main/java/com/example/warehouse/service/ProductService.java
> +                        Comparable lowerValue = value instanceof BigDecimal ? ((BigDecimal) value).subtract(BigDecimal.TEN) : (int) value - 10;
А вот представь у меня количество и цена оба BigDecimal. И я хочу для количества Like делать как +-10%, а для цена +-5%?

2024-05-11 11:45 UTC, GUR-ok commented on src/main/java/com/example/warehouse/service/ProductService.java
> +                        Comparable upperValue = value instanceof BigDecimal ? ((BigDecimal) value).add(BigDecimal.TEN) : (int) value + 10;
Сделай пожалуйста как я показывал решение.

2024-05-11 11:45 UTC, GUR-ok commented on src/main/java/com/example/warehouse/dto/CriteriaSerchDto.java
> +public class CriteriaSerchDto<T> implements Serializable {
По заданию нужно было делать полиморфную десериализацию. Ты по сути сейчас сделал просто один объект на все с private Object value;

2024-05-11 11:45 UTC, GUR-ok commented on src/main/java/com/example/warehouse/service/ProductService.java
> +                    predicate = builder.and(predicate, builder.equal(fieldExpression, value));
тут у тебя проблема будет с LocalDateTime. тебе придется вводить вплоть до миллисекунд. а хотелось бы для LocalDateTime делать только по дате сравнение. Будешь опять тут if городить? нее.

2025-04-20 07:41 UTC, merged